SRC := $(wildcard src/*.cpp)

all:
	g++ -Ires/fonts -Ires/Musics -Ires/Sounds -Ires/Pictures -Iinclude/sdl -Iinclude/headers -Llib -o minimi $(SRC) -DSDL_MAIN_HANDLED -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer